SAIL-Labs/AMICAL

- amical/get_infos_obs.py
- setup.py
revert the workaround introduced in cba9793c54345c2933f889e857537ad0ae2215e3, and properly address the underlying issue: `amical/internal_data` wasn't being installed alongside the package (now it is).
> fix: add internal_data to package at install time

- amical/mf_pipeline/ami_function.py
This is a v2 of #20 because I had to rebase the branch and it closed the other PR (and I don't have permission to re-open). Sorry about that.
Replicating the text from #20 here:
This should fix #19 by using c='None' instead of c='' in the scatter plot of the mask coordinates.
All other diffs in the commit are end-of-line spaces automatically removed by my editor, sorry about that (I can re-push the fix without the space removed if necessary).
> Fix mask coordinate plotting (v2)

- amical/externals/candid/candid.py
Small addition to the `candid.Open` init method to raise an explicit error when the `filename` argument is not an existing file or directory. It makes it clearer for users if the oifits files are not found on disk, instead of raising an `AttributeError` error only when the data is accessed by candid later, as pointed out in #22.
> Handle missing file in candid Open

- amical/mf_pipeline/bispect.py
- amical/tests/test_extraction.py
- amical/tests/test_io.py
This adds a test for the `_add_infos_header` function, making sure its output is compatible with munch by removing astropy `_HeaderCommentaryCards`, as discussed in #31. The SPHERE example still works and now extraction works for mirage simulations (and should work for actual NIRISS data).
> Temporary fix for astropy _HeaderCommentaryCards

- amical/oifits.py
- amical/tests/test_io.py
After talking to @DrSoulain, I added the option to override the "Sydney University" value of "ORIGIN" in the output oifits file. The new behaviour is:
- If `origin` is specified, use this (error is raised if it is not a string).
- If `origin` is None, try to use the value from the input files, fallback to "Sydney University".
I added the corresponding tests in `test_io.py`. I also refactored it slightly to make `cal` a fixture now that it's used in many places.
> Add `origin` keyword to `amical.save()`

- amical/externals/candid/candid.py
This single line is making pdb usable, so `pytest --pdb` is currently useless in AMICAL. Furthermore, changing matplotlib's global state at import time seems like an unreasonable side effect.
Related to #53
> ENH: do not turn pyplot's interactive mode on at import time

- .github/workflows/bleeding-edge.yaml
Add a scheduled daily workflow to run tests against dev versions for
- Python 3.10
- numpy
- astropy
- matplotlib
This will help testing #73 and in general, detect issues (and warnings) from upcoming versions of our dependencies _before_ they are published
The workflow is setup so that it can be manually triggered too
> TST: setup bleeding edge CI

- amical/mf_pipeline/bispect.py
- amical/tests/test_extraction.py
- setup.cfg
This is a follow-up for #60 by @neutrinoceros. As discussed there, I added a warning that commentary cards are removed. I also changed `working version` to `5.0rc1`, the first release candidate with the upstream fix included. I also added tests to 1) check that the card is included in 5.0 and 2) Check that the warning is issued before 5.0.
> ENH: Add conditional to adapt behaviour depending on astropy version and warn user

- amical/data_processing.py
- amical/tests/test_processing.py
- amical/tests/test_tools.py
- amical/tools.py
When playing with simulated NIRISS data, I encountered a few corner cases during the cleaning due to the small size (80x80) of the images. The problems were not caught and resulted in error later when the image was re-used:
- Using an `isz` that went out of bounds gave a non-square array and did not warn the user. After discussing with @DrSoulain, we chose to simply raise and error and suggest maximum possible value to the user.
- Using a sky subtraction (inner) radius that was out of the image was not caught and resulted in a `NaN` value for the whole background. Now, there is a warning and the background subraction is skipped (same behaviour as the previous one if an `IndexError` was caught.
- I also added a warning if the outer sky subtraction radius is out of bounds, to let the user …
> Use more explicit errors and warnings in data cleaning

- amical/oifits.py
- amical/tests/test_io.py
This adds the possibility to give uncalibrated observables (i.e. the output from `amical.extract_bs()`) to `amical.save()` and save them to oifits. While doing this is probably not a good idea for scientific analysis, it can be useful to save the raw observables in a standard format and inspect them later or compare them with similar output other tools.
To avoid rewriting a whole `cal2dict` but for raw observables, I simply defined a `wrap_bs()` function that makes the format of the raw observables compatible with the calibrated ones. Because it's bit of a niche use case, I added a warning that can be silenced with a new keyword argument (`raw`). I have a few questions:
- Is it OK to use `warnings.warn()` for the warning or should I use `cprint()` as in other areas of AMICAL ?
- Is the …
> Enable saving raw observables to oifits files with `amical.save()`

- .github/workflows/bleeding-edge.yaml
- .github/workflows/ci.yml
- .pre-commit-config.yaml
- pyproject.toml
- setup.cfg
Astropy just released wheels for Python 3.10, as did h5py earlier this week, so I think it should be trivial now to declare support for Python 3.10 on AMICAL
> MNT: add explicit support for Python 3.10

- .github/workflows/bleeding-edge.yaml
- pyproject.toml
fix #90
The job will still fail because of deprecation warnings from SciPy, but I'll fix this in a follow up PR
> Fixup bleeding edge ci

- amical/externals/pymask/cpo.py
This should finish fixing bleeding-edge CI, see error : https://github.com/SydneyAstrophotonicInstrumentationLab/AMICAL/runs/4353954995?check_suite_focus=true
I've checked that this works for every version of scipy we supposedly support (it worked on scipy 1.0, which didn't have wheels for Python 3.7 so it's already older than what we need to support)
> TST: fixup deprecated import statement from scipy

- .github/workflows/bleeding-edge.yaml
- .github/workflows/ci.yml
Adding missing __init__.py files where due. The bug was hidden by the way the were invoking pytest (`python -m pytest` instead of `pytest`), see https://docs.pytest.org/en/latest/how-to/usage.html#calling-pytest-through-python-m-pytest
> BUG: fix packaging issue in CLI module

- .github/workflows/bleeding-edge.yaml
- .github/workflows/ci.yml
- .github/workflows/type-checking.yaml
Pyvo maintainers just uploaded some wheels to PyPI, which should resolve the installation issue we faced recently.
See https://github.com/astropy/pyvo/issues/296
> TST: revert a temporary workaround in GH workflows

- amical/data_processing.py
- amical/tests/test_processing.py
This would allow setting the bad pixel map or the `add_bad` list separately for each frame (fixes #81). I am making it it a draft until #76 is merged, but I'm open to suggestions in the meantime. The changes are compatible with the previous 2d-only behaviour, simply making 3d arrays an extra option. Short summary of changes:
- Bad pixel map `bad_map` can now be either a 2d array with one map for all frames or 3d array with one map per frame
- `add_bad` can now either be a list of bad pixel index pairs (e.g. `[(1,2), (2, 3)]`) applied to all frames, or a list of such lists (with total length equal to the number of frames). (2d and 3d arrays work as well)
- There are tests for `fix_bad_pixels()` and `clean_data()` (mainly for the bad pixel correction aspect).
> Per-frame bad pixel correction

- amical/data_processing.py
- amical/tests/test_processing.py
- amical/tests/test_tools.py
- amical/tools.py
This adds the features described in #80. Namely:
- It changes the order of `crop_max()`and `sky_correction()` calls in `clean_data`, making the whole (non-cropped) image available for background subtraction (and not changing the default behaviour if `r1`and `dr`are within the cropped image. The center is still found before subtraction, to center the ring around the center.
- It adds an optional `mask` option in sky correction. This allows users to provide a boolean mask to use any combination of pixels for the background subtraction. Having two options (`r1` and `dr` or `mask`) for sky correction, it seemed safer to set them all to None and force user to explicitly specify the parameters. I added deprecation warnings and made the functions fall back to the default for now when no …
> Subtract sky from full image and allow arbitrary mask

- amical/mf_pipeline/bispect.py
- amical/tests/test_io.py
The kwargs `verbose` = False now suppress the tqdm progress bar (as well as the standard stdout). This feature was requested in #121 and allow to run amical in "quiet mode".
> Add quiet mode in extraction step

- pyproject.toml
fix an instability seen in bleeding-edge CI that we have no control over
see https://github.com/matplotlib/matplotlib/pull/22766 for context
> filter upstream depr warning

- amical/mf_pipeline/bispect.py
- pyproject.toml
This should be fully backwards compatible for previously supported versions of PyPDF2
> MNT: fix a future incompatibility with PyPDF2

- amical/oifits.py
- amical/tests/test_io.py
When trying to use AMICAL outputs with [fouriever](https://github.com/kammerje/fouriever), I got an error saying the telescope was unknown. The TELESCOP keyword was an empty string in the oifits even though the initial data had `TELESCOP='JWST'`. The issue seems to be that the telescope is saved in the info dictionary with a lowercase key (like `date-obs`), so it was not found when trying to pass it to the oifits. This fixes the issue by using lowercase. I also added a fallback option for INSTRUME to get the right instrument from the info dict.
I saw that the unit test function for saving raw oifits is commented out, so I did not add a failing test for this.
> Add telescope and instrument to raw oifits

- amical/mf_pipeline/bispect.py
- setup.cfg
fix deprecation warnings seen in recent CI jobs
For context: https://pypdf2.readthedocs.io/en/latest/meta/CHANGELOG.html#version-3-1-0-2022-12-23
> BLD: migrate from PyPDF2 (deprecated) to its replacement pypdf

- amical/get_infos_obs.py
- pyproject.toml
- requirements/typecheck.txt
based on #158 
follow up to #155
Rationale: see warning at the top of [this page](https://setuptools.pypa.io/en/latest/pkg_resources.html)
> BLD: drop pkg_resources as a dependency on Python 3.8

- amical/get_infos_obs.py
- amical/mf_pipeline/bispect.py
- amical/tests/test_extraction.py
- pyproject.toml
> BLD: require astropy>=5.0, drop dependency on packaging

- amical/analysis/fitting.py
- amical/get_infos_obs.py
fix #171
validation on my fork at https://github.com/neutrinoceros/AMICAL/actions/runs/4806682041
> BUG: fix implicit conversion from array to scalar (deprecated in numpy 1.25)

- amical/analysis/fitting.py
This resolves a failure seen in today's weekly CI job with upstream dev versions.
The cause of the regression is a change of implementation in numpy.cos which causes new floating point errors for `np.cos(0)` (see https://github.com/numpy/numpy/issues/23773 and https://github.com/numpy/numpy/pull/23399)
Seeing this can probably not be adressed in numpy itself, let's add some margin of error to the check.
I also fixed another bug where an angle in radian (`posang`) was compared to `180`.
> BUG: allow floating point errors at machine precision when comparing result from np.cos with 1.0

- .github/workflows/bleeding-edge.yaml
this should drastically reduce testing build time
> TST: use nightly builds for numpy matplotlib and scipy

- .github/workflows/bleeding-edge.yaml
- amical/mf_pipeline/bispect.py
getting around a new deprecation warning:
`DeprecationWarning: PdfMerger is deprecated and will be removed in pypdf 5.0.0. Use PdfWriter instead.`
> RFC: avoid deprecated pypdf API

- .github/dependabot.yml
tentative fix for #181 following the answer I got from github's support team, which I copy verbatim here:
> Lauren (GitHub Support) Sep 6, 2023, 12:44 PM UTC
Hello Clément,Thank you for contacting GitHub support. It looks like Dependabot didn't pick up your dependabot.yml file, but I don't see any issues with it that would prevent it from processing. Can you try updating the file with something small like a new comment line or reverse the order of the package-ecosystem sections? This should force Dependabot to re-process the file and will hopefully recognize it.Kind regards,Lauren
> MNT: noop update dependabot.yml

- amical/_cli/commands/calibrate.py
- amical/_cli/commands/clean.py
- amical/_cli/commands/extract.py
- amical/_rich_display.py
- amical/analysis/easy_candid.py
- amical/analysis/fitting.py
- amical/data_processing.py
- amical/externals/pymask/cpo.py
- amical/get_infos_obs.py
- amical/ifu.py
- amical/mf_pipeline/ami_function.py
- amical/mf_pipeline/bispect.py
- amical/mf_pipeline/idl_function.py
- amical/oifits.py
- amical/tests/test_io.py
- amical/tests/test_rich_display.py
- amical/tools.py
- pyproject.toml
Reduce the number of dependencies: drop dependency on `tabulate` (replaced by astropy.table.Table), `termcolor` and `tqdm` (both replaced by `rich`)
close #182
> ENH: add drop-in replacement for tabulate

- amical/data_processing.py
- amical/tests/test_processing.py
This PR implements a bit more consistent use of the `isz` parameter when the argument is set to `None`.
Currently, the value could be set to `None` in `select_clean_data`, in which case the original image size is used without searching for a new image center.
The `show_clean_params` did however still search for a new image center with `isz=None`. I have changed the way this is implemented, so the original image center is used in that case.
I have also added/changed the default value of `isz` in `show_clean_params` and `select_clean_data` to `None`. Before, the default value of `isz` was only set to `None` in `clean_data`.
> BUG: fix calling `select_clean_data` with default `isz`

- .github/workflows/bleeding-edge.yaml
- amical/tests/test_processing.py
I noticed that pytest 8.0.0rc1 breaks AMICAL's tests. I'll be working on fixing this here.
> TST: test against pytest pre-releases

- pyproject.toml
This follows two changes in ruff's configuration:
- ruff now properly detects our minimum supported Python version so it doesn't need an extra option
- most rules have been moved to a `ruff.lint` section to clarify the distinction with `ruff.format`
> MNT: migrate ruff config

- .github/workflows/ci.yml
- pyproject.toml
- uv.lock
I bootstrapped lower bounds with the following strategy:
- if the dependency has extension modules, take the oldest version that has cp310 wheels
- otherwise, take a guess and try a version that was released around the same time as astropy 5.0 (nov 2021)
> DEP: add missing dependency lower bounds and test them

- .github/workflows/bleeding-edge.yaml
Tentatively address an issue [seen in CI](https://github.com/SAIL-Labs/AMICAL/actions/runs/16460852286/job/46527651401) where nightly builds of at least numpy and matplotlib are apparently ignored. This manifests as a deprecation warning in pillow, triggered by matplotlib, and that I already fixed upstream a couple weeks ago.
> TST: explicitly upgrade lock file as a separate step in bleeding edge CI
