amical/__init__.py
amical/analysis/candid.py
amical/analysis/easy_candid.py
amical/analysis/easy_pymask.py
amical/analysis/pymask/__init__.py
amical/analysis/pymask/cp_tools.py
amical/analysis/pymask/cpo.py
amical/analysis/pymask/oifits.py
amical/analysis/pymask/oitools.py
amical/analysis/pymask/pol_tools.py
amical/analysis/pymask/x_y_plot.py
amical/mf_pipeline/ami_function.py
amical/mf_pipeline/bispect.py
amical/tests/test_io.py
amical/tools.py
example_NIRISS.py
example_SPHERE.py
example_analysis.py
setup.py

Add Pymask solution to analyze NRM data of binary stars.

Add pymask

---

README.md
amical/__init__.py
amical/analysis/candid.py
amical/analysis/easy_candid.py
amical/analysis/easy_pymask.py
amical/analysis/pymask/__init__.py
amical/analysis/pymask/cp_tools.py
amical/analysis/pymask/cpo.py
amical/analysis/pymask/oitools.py
amical/analysis/pymask/pol_tools.py
amical/analysis/pymask/x_y_plot.py
amical/calibration.py
amical/core.py
amical/dataProcessing.py
amical/data_processing.py
amical/get_infos_obs.py
amical/mf_pipeline/ami_function.py
amical/mf_pipeline/bispect.py
amical/oifits.py
amical/tests/test_io.py
amical/tools.py
example_NIRISS.py
example_SPHERE.py
example_analysis.py
setup.py

New features :
--------------
- Add compatibility to use the data format of MIRAGE simulations (NIRISS) after the stage 1 and 2 JWST pipeline,
- Add function to replace bad pixels (from a bad pixel map previously computed) using kernel-gaussian convolution interpolation,
- Simplify the data checker function (check_data_params()) to easily check the used parameters before data cleaning (resize, background, etc.)
- Change some function/module names to agreed with pep8 convention.

Add cleaning mirage data and change naming convention.

---

amical/analysis/candid.py
amical/analysis/pymask/cp_tools.py
amical/analysis/pymask/oitools.py
amical/analysis/pymask/pol_tools.py
amical/analysis/pymask/x_y_plot.py
amical/mf_pipeline/ami_function.py
amical/mf_pipeline/bispect.py

Fix all problems detected by
```bash
vulture --min-confidence 100 amical
```
Mostly, it's about removing brain dead unreachable code (following a `if False` or a `raise` or `return` statement for instance).
I also found some print statements (python 2) and added some parenthesis for better compatibility against Python 3.
I advise this is reviewed carefully. Maybe some of the dead code is actually meant to be active but was only broken by unsatisfiable conditions.

cleanup: remove dead code

---

.gitignore
amical/tests/conftest.py
amical/tests/test_io.py

refactoring tests with pytest fixtures to avoid repeated code and repeated setup. Testing time is roughly divided by 2

tests: clean pytest fixtures

---

.github/workflows/ci.yml

switch from push to pull-request as a trigger

ci: fix gh workflow

---

amical/analysis/easy_candid.py
amical/externals/candid/__init__.py

The intention is to fix the broken packaging strategy for the external subdirectories

hotfix external packaging for candid

---

.pre-commit-config.yaml
doc/example_NIRISS.py
doc/example_SPHERE.py
doc/example_analysis.py
doc/tutorial.md

fix pre-commit exclude pattern

---

.pre-commit-config.yaml
doc/example_NIRISS.py
doc/example_SPHERE.py
doc/example_analysis.py
doc/tutorial.md

apply black to documentation (please merge #39 first)

add blacken-docs to pre-commit

---

README.md
amical/__init__.py
setup.cfg

This is a prep step that should be merged right before we publish on Pypi !

prep for Pypi publication

---

README.md

Remove isort badge and make installation instructions compatible on systems where the default Python executable is Python 2

DOC: minor corrections to README.md

---

amical/calibration.py
amical/data_processing.py
amical/externals/candid/candid.py
amical/externals/pymask/cp_tools.py
amical/externals/pymask/x_y_plot.py
amical/get_infos_obs.py
amical/ifu.py
amical/mf_pipeline/bispect.py
amical/oifits.py
amical/tests/test_io.py
amical/tools.py
pyproject.toml

TST: treat warnings as errors

---

.github/workflows/bleeding-edge.yaml
README.md

Also fixup a left over from my copypasta (cmyt -> amical) and add a cool badge to the README

TST: fixup bleeding edge CI workflow

---

.github/workflows/bleeding-edge.yaml
pyproject.toml

This will fix the bleeding edge job

TST: use nightly wheels for numpy

---

.github/workflows/bleeding-edge.yaml
pyproject.toml

Reverts SydneyAstrophotonicInstrumentationLab/AMICAL#88
Apparently it didn't solve the issue and only delayed its resolution.

Revert "TST: use nightly wheels for numpy"

---

.github/workflows/cd.yml
.github/workflows/ci.yml
.pre-commit-config.yaml
amical/__init__.py
setup.cfg

Change minimum support to Python 3.8 as recommended (https://numpy.org/neps/nep-0029-deprecation_policy.html).

Change version support 3.8+

---

.github/workflows/ci.yml

TST: set a stricter timeout for CI

---

amical/analysis/easy_candid.py

BUG: fix some bugs detected with type annotations

---

.github/workflows/bleeding-edge.yaml
.github/workflows/ci.yml
.github/workflows/type-checking.yaml

TST: drop testing on Python 3.9

---

pyproject.toml

fix #123
ping @vandalt for confirmation

TST: generalize a regexp for a category of warnings to be ignored in tests

---

pyproject.toml

Fix a typo from #125

---

.pre-commit-config.yaml
amical/analysis/easy_candid.py
amical/analysis/fitting.py
amical/analysis/models.py
amical/calibration.py
amical/data_processing.py
amical/dpfit.py
amical/externals/candid/candid.py
amical/externals/pymask/cp_tools.py
amical/externals/pymask/oifits.py
amical/externals/pymask/oitools.py
amical/externals/pymask/x_y_plot.py
amical/mf_pipeline/ami_function.py
amical/mf_pipeline/bispect.py
amical/mf_pipeline/idl_function.py
amical/oifits.py
amical/tools.py

This update is necessary because newest versions of click break black (see https://github.com/psf/black/issues/2964)
updating black is also going to cause many small style changes that came with black 22

pre commit auto update

---

amical/analysis/easy_candid.py
amical/analysis/easy_pymask.py
amical/analysis/fitting.py
amical/analysis/models.py
amical/calibration.py
amical/data_processing.py
amical/dpfit.py
amical/externals/candid/candid.py
amical/externals/pymask/__init__.py
amical/externals/pymask/cp_tools.py
amical/externals/pymask/cpo.py
amical/externals/pymask/oifits.py
amical/externals/pymask/x_y_plot.py
amical/get_infos_obs.py
amical/mf_pipeline/ami_function.py
amical/mf_pipeline/bispect.py
amical/mf_pipeline/idl_function.py
amical/oifits.py
amical/tools.py

fix #140
Got the import time from 2s down to <150ms on my machine. Now numpy is by far the dominant contributor to amical's import time

ENH: load heavy dependencies lazily

---

README.md
amical/__init__.py
amical/data_processing.py
amical/get_infos_obs.py
amical/ifu.py
amical/mf_pipeline/ami_function.py
amical/mf_pipeline/bispect.py
amical/oifits.py
amical/tests/test_io.py
amical/tests/test_processing.py
amical/tests/test_tools.py
doc/example_IFS.py
setup.cfg

As noted in #145, the cleaning step of AMICAL is not compatible with the standard IFU data obtained with VLT/SPHERE. For now, we add some compatibility keywords to deal with such types of data. The main idea is to process each spectral channel individually by the use of `i_wl` keyword.

ENH: Add IFU compatibility for SPHERE

---

amical/calibration.py
amical/externals/munch/LICENSE
amical/externals/munch/__init__.py
amical/mf_pipeline/ami_function.py
amical/mf_pipeline/bispect.py
amical/mf_pipeline/idl_function.py
amical/oifits.py
amical/tests/test_cli.py
amical/tests/test_extraction.py
amical/tests/test_io.py
amical/tools.py
pyproject.toml

testing the bleeding edge workflow on my fork at https://github.com/neutrinoceros/AMICAL/actions/runs/4183370124

BLD: vendor a minimal version of munch

---

pyproject.toml

TST: filter a DeprecationWarning triggered from numpy via h5py

---

amical/externals/pymask/cp_tools.py

BUG: fix compatibility with corner 2.2.2

---

amical/externals/pymask/oifits.py

for context: https://github.com/numpy/numpy/pull/24376

BUG: fix an incompatibility with numpy 2.0 (np.string_ was removed)

---

amical/_cli/commands/calibrate.py
amical/_cli/commands/clean.py
amical/_cli/commands/extract.py

ENH: write CLI error messages to stderr

---

.github/workflows/bleeding-edge.yaml

TST: test bleeding-edge dependencies with latest Python

---

.github/workflows/ci.yml

TST: fix a mistake in CI configuration

---

amical/oifits.py

[example logs](https://github.com/SAIL-Labs/AMICAL/actions/runs/12900348875/job/35970675224)

BUG: handle deprecation warning from astroquery 0.4.8

---

pyproject.toml

BLD: switch build backend to `flit-core`

---

pyproject.toml

BLD: require flit-core 3.11 or newer
